language: node_js

node_js:
  - 'lts/*'
  - 'stable'

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install imagemagick ghostscript poppler-utils graphicsmagick

before_script:
  - npm link
