name: Test

on:
  workflow_dispatch: null
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Tese
        run: docker build  -t relaxedjs-test . && docker run -it relaxedjs-test
