name: Test

on:
  workflow_dispatch: null
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    container: dpokidov/imagemagick
    strategy:
      matrix:
        include:
          - node-version: 16.x
            targets: node16
          - node-version: 18.x
            targets: node18
          - node-version: 20.x
            targets: node20
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test
